[build]
  command = "bun install --frozen-lockfile && bun run --cwd packages/core build && bun run --cwd packages/web build"
  publish = "packages/web/.next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index"
  status = 200
